apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-app-deployment
spec:
  replicas: 2 # Let's run two copies for high availability!
  selector:
    matchLabels:
      app: my-chat-app
  template:
    metadata:
      labels:
        app: my-chat-app
    spec:
      containers:
        - name: my-chat-app
          image: 373317459404.dkr.ecr.eu-west-2.amazonaws.com/my-chat-app:latest # My ECR Image
          ports:
            - containerPort: 8080
          env:
            - name: REDIS_ENDPOINT_URL
              value: "redis-service:6379" # <-- This is the "magic glue"!
